set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(EDGE_PROBE_TARGET_TRIPLE aarch64-linux-gnu)

set(CMAKE_C_COMPILER ${EDGE_PROBE_TARGET_TRIPLE}-gcc)
set(CMAKE_CXX_COMPILER ${EDGE_PROBE_TARGET_TRIPLE}-g++)

set(CMAKE_FIND_ROOT_PATH
    /usr/${EDGE_PROBE_TARGET_TRIPLE}
    /usr/include/${EDGE_PROBE_TARGET_TRIPLE}
    /usr/lib/${EDGE_PROBE_TARGET_TRIPLE})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_LIBRARY_ARCHITECTURE ${EDGE_PROBE_TARGET_TRIPLE})
